on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: "Windows - Latest MSVC"
            os: windows-latest
            artifact: Windows-MSVC.tar.xz
            build_type: Release
            cc: cl
            cxx: cl
          - name: "Ubuntu - Latest GCC"
            os: ubuntu-latest
            build_type: Release
            cc: gcc
            cxx: g++
          - name: "MacOS - Latest clang"
            os: macos-latest
            build_type: Release
            cc: clang
            cxx: clang++

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install conan
        run: pip install conan
      - name: Versions
        run: |
          python --version
          pip --version
          cmake --version
      - name: Build
        run: |
          mkdir build
          cd build
          conan install ..
          cmake ..
          cmake --build .
      - name: Test
        run: |
          cd build
          ctest --verbose
